uploads = []
outputs = []

[[generated]]
id = "s-Rh58diIZIy3yi9ZxzM6"
uri = "file://artifacts/football-platform/src/assets/signal-terminal-logo.png"
type = "image"
title = "Signal Terminal app logo"

[[generated]]
id = "q3_vwcC9a2s1wDysUVVFG"
uri = "file://artifacts/football-platform/src/assets/signal-terminal-favicon.png"
type = "image"
title = "Signal Terminal favicon icon"
