// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/football-platform/Dashboard.tsx": () => import("../components/mockups/football-platform/Dashboard.tsx"),
  "./components/mockups/football-platform/MatchLive.tsx": () => import("../components/mockups/football-platform/MatchLive.tsx"),
  "./components/mockups/football-platform/MatchPre.tsx": () => import("../components/mockups/football-platform/MatchPre.tsx")
};
